site_name: Mayoroffk
site_url: https://ft256.ru/
copyright: Copyright &copy; 2022 Mayorov Kirill
theme:
  name: material
  language: ru
  favicon: images/favicon.png
  logo: images/favicon.png
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
extra:
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/aerolight
nav:
  - Домашняя страница: index.md
extra_css:
  - stylesheets/extra.css
